# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  
    if Vagrant.has_plugin? "vagrant-vbguest"
      config.vbguest.no_install = true
      config.vbguest.auto_update = false
      config.vbguest.no_remote = true
    end
  
    # Configuración para la máquina servidorUbuntu
    config.vm.define :servidorUbuntu do |servidorUbuntu|
      servidorUbuntu.vm.box = "bento/ubuntu-22.04"
      servidorUbuntu.vm.network :private_network, ip: "192.168.100.3"
      servidorUbuntu.vm.hostname = "servidorUbuntu"
      
      # Reenvío del puerto para acceder a Jupyter Notebook
      servidorUbuntu.vm.network "forwarded_port", guest: 8888, host: 8888, auto_correct: true
  
      servidorUbuntu.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end
      servidorUbuntu.vm.provision "shell", path: "script.sh"
    end
  end
  